version: '2'


services:
  api:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - "4040:4040"
    env_file:
      - .env
    environment:
      - MONGO_HOST=mongodb://mongo/api
      - DEBUG=api:*
    links:
      - mongo
      - redis
  mongo:
    image: "mongo:3.4.2"
    ports:
      - "27017:27017"
  redis:
    image: "redis:latest"

